;; -*- mode: eask; lexical-binding: t -*-

(package "eglot-gopls"
         "0.0.1"
         "Go gopls integration with eglot")

(website-url "https://github.com/zsxh/eglot-gopls")
(keywords "eglot" "tools")

(package-file "eglot-gopls.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "30.1")
(depends-on "compat" "30.1.0.0")
(depends-on "eglot" "1.17.30")
